### PR TITLE
Rework and cleanup components and optionals

### PR DESCRIPTION
**Pull request by Mike-MF**
**Should not be merged until Arma 2.14**

Also utilised CUP Loadorders for requiredAddons where necessary.

We are now officially out of optionals.

- Removes RHS compats (outdated)
- Removes AV8B
- Removes CUP heavylifter compatibility
- Removed EricJs taliban compats (mod isn't available anymore)
- Removed Kunduz Gridlines (the map has several reuploads, they all have severe issues, gridlines only affects 1 of them)
- Removed Aegis compats
- Removed CUP ACRE compat (Only covered CUP SUV.)
- Removed BWA3 ACRE compat (Only covered Eagles)

`skipWhenMissingDependencies`:
- Project Infinite ACE compats now in Main (Merged into one)
- MELB now in main
- Western Sahara compats now in main.
- ACRE compat now in main.
- MILGP ACE compat now in main.
- CUP ACE compat / no uniform restrictions now in main. (Merged into one)

### CODE REVIEW

**Comment by jonpas** [comment]
This will mark v2 release of Theseus Mods with a major cleanup of unused systems and compatibilities/optionals.

Latest released version will be tagged with `v1` for anyone searching for any old tweaks they may want to take into their own mods. This mod will shift more into an internal use, but still be public and be able to be used by anyone, it will just be cleaned out more often to only contain what we use in Theseus at any given time.

> Removes RHS compats (outdated)
> Removes AV8B
> Removes CUP heavylifter compatibility

Only had Heavy Lifter compatibility, which is outdated and getting removed/replaced with a simpler system.

> Removed EricJs taliban compats (mod isn't available anymore)

https://steamcommunity.com/sharedfiles/filedetails/?id=668919514

We are however not using that mod for ages now and those two optionals (Armed and No Uniform Restrictions) are possibly outdated. Good to remove anyways for v2.

> Removed Aegis compats

Compats had Heavy Lifter only, same as above.

ACE Hearing and No Uniform Restrictions should be put into ACE3 as we won't use it.

> `skipWhenMissingDependencies`

- `a3_acre_racks` -> `acre` (we can add subconfigs for X mod + ACRE stuff later)
- `compat_cup` -> `cup`
- `compat_melb` -> `melb`
- `compat_projectinfinite` -> `projectinfinite` (or `bnae`?) - also subconfigs or just keep as one?
- `compat_ws` -> delete it, only contains Heavy Lifter stuff
- `milgp_ace_hearing` -> `milgp` (with subconfigs)
- `ws_nouniformrestrictions` -> `ws`

> No Uniform Restrictions

Those compats should ideally require `ace_nouniformrestrictions`, so sub-config? Or maybe better to have a `nouniformrestrictions` component that just requires all of our mods. Less sub-configs to deal with. Other things could work similarly?

Or we just don't care about separating and only load the thing if all dependencies are there, since we are doing away with "anyone can directly use our components". Basically do what ArmaForces does.

---

Additionally, delete components:
- Heavy Lifter
- Insignia (handled through Armory for years now, don't forget the setting in CBA Settings)

CBA Settings component shouldn't have any Mods settings in it, those should be changed to default where the setting is created.

**Comment by Mike-MF** [comment]
Have a look at `COMPONENT_BEAUTIFIED` for all the components that you listed in your comment. I don't know what you want those to be.

**Comment by jonpas** [comment]
Yeah, but after things like No Uniform Restrictions and ACE Hearing stuff is decided.

> Those compats should ideally require `ace_nouniformrestrictions`, so sub-config? Or maybe better to have a `nouniformrestrictions` component that just requires all of our mods. Less sub-configs to deal with. Other things could work similarly?
>
> Or we just don't care about separating and only load the thing if all dependencies are there, since we are doing away with "anyone can directly use our components". Basically do what ArmaForces does.

Just going for that last part then?

---

As for naming, we might not only have compatibility in eg. `cup` but also other tweaks, that's why I wanted to avoid `compat_` naming.

Just do the same for beautified, `ws` is `Western Sahara`, no need to complicate, it's just another component.

---

Side-note: I wonder if we can somehow use this feature to use the exact same Mods packages for Public repo (where we don't load a few components). I don't think so though.

---

You also missed the very last section of my previous comment. :P

**Comment by Mike-MF** [comment]
Think I got everything you listed, including what I missed before

**Review by jonpas — APPROVED** [review]

**Pull request merged**
