### PR TITLE
Add example Insurgents gear mission config

### PR DESCRIPTION
**Pull request by veteran29**
**When merged this pull request will:**
- title

### CODE REVIEW

**Comment by jonpas** [comment]
Feel free to merge when you are done. :D

**Comment by veteran29** [comment]
> Feel free to merge when you are done. :D

The base branch restricts merging to authorized users. Learn more about protected branches. :(

**Comment by veteran29** [comment]
Can be merged, I don't see any errors.

**Comment by jonpas** [comment]
Should be able to merge now.

**Pull request merged**
