### PR TITLE
Mission - Add side relations function

### PR DESCRIPTION
**Pull request by Mike-MF**
Adds easy to use side relations function

### CODE REVIEW

**Review by jonpas — COMMENTED** [review]
I don't really see the point of this function. All it does is change 2 lines into 1 line.

**Comment by Mike-MF** [comment]
So i can be lazy and
`[] call TAC_mission_fnc_sideRelations;`

Also means I don't have to constantly wrap stuff in `if (isServer)` or check other people are doing the same.

Mostly it'll be on the wiki so people know it exists and can use it and don't ask me questions ;)

**Review by jonpas — COMMENTED** [review]
> Call from initServer

So the `isServer` check doesn't matter at all and is redundant.

Why not just put this on the wiki?
```sqf
west setFriend [resistance, 0];
resistance setFriend [west, 0];
```

There is no use in this function other than additional overhead.

**Comment by Mike-MF** [comment]
Closing because JJ hates making my life easy

**Pull request closed without merging**
