### PR TITLE
Mission - Fix Hunt Group not showing count

### PR DESCRIPTION
**Pull request by Mike-MF**
**When merged this pull request will:**
- When calling `monitorUnits` locally it shows `scalar` instead of a count, it bothers me so now it's fixed.
- Also moves FPS to first case because it fits properly.

### CODE REVIEW

**Comment by jonpas** [comment]
Now it will show `0`? That is also incorrect!

**Comment by Mike-MF** [comment]
It's only updated on the server to prevent publicVariable shenanigans, but 0 makes everything fit nicely where as scalar cuts off the FPS and it bothers me.

**Comment by jonpas** [comment]
But it's not `0`.

**Comment by Mike-MF** [comment]
But it's also only tracked on the server.

Shouldn't be locally using it for checking hunt groups anyway, so it will be wrong but so is not watching via server!

I just use it to see people's FPS

**Comment by jonpas** [comment]
If function should not be used locally, then it should exit and not display "wrong" values.

If only hunt groups should not work locally, then instead of showing a number, just show `N/A`, that's a simple `format ["... %1 ...", [_groups, "N/A"] select (isServer)]`

**Review by jonpas — APPROVED** [review]

**Pull request merged**
