### PR TITLE
Settings - Add ACE3 Medical Fatal Damage Source

### PR DESCRIPTION
**Pull request by jonpas**
**When merged this pull request will:**
- Title

### CODE REVIEW

**Comment by TyroneMF** [comment]
Setting is hit or miss, sometimes it kills AI others they just go into unconscious.

https://i.gyazo.com/c8d38a278f20d31015827a90a7b332e9.png

**Comment by TyroneMF** [comment]
Probably best to test this on a larger scale than me locally. Could run something mid-week to test with volunteers.

**Comment by jonpas** [comment]
No need to merge, test it by setting it in a mission.

Additionally, test just disabling AI Unconsciousness if this doesn't work. Or if you want more in-depth, combine this setting with AI Damage Threshold.

**Comment by TyroneMF** [comment]
I'll work up some non-chronos scenarios with multiple settings and see where we land.

**Comment by TyroneMF** [comment]
I ran this on my last mission, seemed to work out fine.

**Pull request merged**
