### PR TITLE
CBA Settings - Use Medics equipment first

### PR DESCRIPTION
**Pull request by TyroneMF**
- Changes from using Patients medical equipment first, to medics.

### CODE REVIEW

**Comment by jonpas** [comment]
Approved by the Master Medic @JoramD0?

**Comment by JoramD0** [comment]
Slightly concerned about it but I wouldn't mind running this as a test

**Comment by jonpas** [comment]
Status @TyroneMF @JoramD0 ?

**Comment by TyroneMF** [comment]
Can run this as a test for Saturday, my thoughts on this are basic;

Infantry runs out of medical supplies > take them from medic.

This just cuts out all that and uses the medics first.

**Comment by JoramD0** [comment]
I am fine with running this as a test, I am still not convinced this is a good idea though

**Pull request closed without merging**
